#### Câu 1: Numpy Array

```
Cho dữ liệu data với các giá trị như sau : 

data =[ 30, 22, 47, 20, 46, 47, 37, 24, 40, 12, 43, 45, 44, 48, 24, 30, 15, 28, 21, 29, 17, 24, 41, 33, 2]
```


In [1]:
import numpy as np

In [2]:
# khởi tạo list data theo các giá trị đề bài cho trước
data = [30, 22, 47, 20, 46, 47, 37, 24, 40, 12, 43, 45, 44, 48, 24, 30, 15, 28, 21, 29, 17, 24, 41, 33, 23]
data

[30,
 22,
 47,
 20,
 46,
 47,
 37,
 24,
 40,
 12,
 43,
 45,
 44,
 48,
 24,
 30,
 15,
 28,
 21,
 29,
 17,
 24,
 41,
 33,
 23]

In [3]:
# khởi tạo numpy array từ list data
np_arr = np.array(data)
np_arr

array([30, 22, 47, 20, 46, 47, 37, 24, 40, 12, 43, 45, 44, 48, 24, 30, 15,
       28, 21, 29, 17, 24, 41, 33, 23])

In [4]:
# in kết quả gồm:
# toàn bộ mảng, 5 giá trị đầu tiên, 5 giá trị cuối cùng
print("Mảng arr : ", np_arr) # toàn bộ mảng
print("5 phần tử đầu tiên của mảng: ", np_arr[:5:]) # 5 phần tử đầu tiên
print("5 phần tử cuối cùng của mảng: ", np_arr[-5::]) # 5 phần tử cuối cùng

Mảng arr :  [30 22 47 20 46 47 37 24 40 12 43 45 44 48 24 30 15 28 21 29 17 24 41 33
 23]
5 phần tử đầu tiên của mảng:  [30 22 47 20 46]
5 phần tử cuối cùng của mảng:  [17 24 41 33 23]


##### Từ mảng 1 chiều arr, chuyển đổi thành mảng 2 chiều arr_2d có kích thước 5x5

In [5]:
# chuyển từ 1D Array sang 2D Array có kích thước 5x5
np_arr_2d = np_arr.reshape(5,5)
np_arr_2d

array([[30, 22, 47, 20, 46],
       [47, 37, 24, 40, 12],
       [43, 45, 44, 48, 24],
       [30, 15, 28, 21, 29],
       [17, 24, 41, 33, 23]])

In [6]:
# In ra kết quả 2D array vừa tạo
print("Mảng 2 chiều:")
print(np_arr_2d)

Mảng 2 chiều:
[[30 22 47 20 46]
 [47 37 24 40 12]
 [43 45 44 48 24]
 [30 15 28 21 29]
 [17 24 41 33 23]]


##### Lọc và in ra các phần tử có giá trị là số chẵn và số lẻ trong arr_2d

In [7]:
arr_odd_number = np_arr_2d[np_arr_2d % 2 != 0] # tạo mảng số lẻ
arr_even_number = np_arr_2d[np_arr_2d % 2 == 0] # tạo mảng số chẳn

print("Các phẩn tử có giá trị là số lẻ : ")
print(arr_odd_number)
print("Các phẩn tử có giá trị là số chẳn : ")
print(arr_even_number)

Các phẩn tử có giá trị là số lẻ : 
[47 47 37 43 45 15 21 29 17 41 33 23]
Các phẩn tử có giá trị là số chẳn : 
[30 22 20 46 24 40 12 44 48 24 30 28 24]


##### Đếm số phần tử chẵn và số phần tử lẻ có trong mảng arr_2d 

In [8]:
print("Số lượng phần tử có giá trị chẵn: ", arr_even_number.size)
print("Số lượng phần tử có giá trị lẻ: ", arr_odd_number.size)

Số lượng phần tử có giá trị chẵn:  13
Số lượng phần tử có giá trị lẻ:  12


##### Thay thế các giá trị chẵn trong mảng arr_2d bằng 0 và thay thế các giá trị lẻ trong mảng arr_2d bằng 

#####  và in ra kết quả 

In [9]:
np_arr_2d[np_arr_2d % 2 == 0] = 0 # chuyển giá trị của mảng là số chẳn thành 0
np_arr_2d[np_arr_2d % 2 != 0] = 1 # chuyển giá trị của mảng là số lẻ thành 1
print("Mảng 2 chiều sau khi thay thế: ")
np_arr_2d

Mảng 2 chiều sau khi thay thế: 


array([[0, 0, 1, 0, 0],
       [1, 1, 0, 0, 0],
       [1, 1, 0, 0, 0],
       [0, 1, 0, 1, 1],
       [1, 0, 1, 1, 1]])